apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oa2x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-oa2x@sha256:90489eb02da7e44c2fc68c68447fc1089e1ee4dfb3cfd84cfc64a4183b0050a1
        name: my-nodejs
        resources: {}
status: {}
